template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: {{ .Values.gitRepo.name }}
    type: GitRepo
    configuration:
      path: {{ .Values.gitRepo.path }}
      # branches:
      #   include: main
      gitProvider: {{ .Values.gitProvider }}

  # Build info for the published Go app
  - name: {{ .Values.build.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}
      # buildName and buildNumber are used for inputResources
      # but these are overwritten with pipelines name when creating (as outputResources)
      # buildName: {{ .Values.build.name }}


pipelines:
  - name: {{ .Values.build.name }}
    steps:
      - name: go_build
        type: GoBuild
        configuration:
          sourceLocation: .
          resolverRepo: {{ .Values.artifactoryRepo.resolver.name }}
          noRegistry: true
          inputResources:
            - name: {{ .Values.gitRepo.name }}
          integrations:
            - name: {{ .Values.artifactory }}

      - name: go_publish_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: go_build
          targetRepository: {{ .Values.artifactoryRepo.targetBinary.name }}
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: go_publish_binary
          outputResources:
            - name: {{ .Values.build.name }}
